name: speffo
description: "A Project That Helps Community."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/logo/
    - assets/media/


  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans/NotoSans-Black.ttf
          weight: 900


